// Code generated by "stringer -type=ingressGroup"; DO NOT EDIT.

package main

import "strconv"

const _ingressGroup_name = "TLSOptionalTLSRequired"

var _ingressGroup_index = [...]uint8{0, 11, 22}

func (i ingressGroup) String() string {
	if i >= ingressGroup(len(_ingressGroup_index)-1) {
		return "ingressGroup(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ingressGroup_name[_ingressGroup_index[i]:_ingressGroup_index[i+1]]
}
